baseURL       = 'https://brick.camp/'
languageCode  = 'en-us'
title         = 'BrickCamp'
enableGitInfo = true

[build]
  [build.buildStats]
    enable = true

[caches]
  [caches.getresource]
    dir = ':resourceDir/_req'

[imaging]
  anchor = 'Center'
  bgColor = '#ffffff'
  hint = 'drawing'
  quality = 95
  resampleFilter = 'Lanczos'

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.145.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[taxonomies]
  part = 'parts'
  size = 'size'
  uses = 'uses'
  tag  = 'tags'

[uglyURLs]
  _data = true