baseURL       = 'https://brick.camp/'
languageCode  = 'en-us'
title         = 'BrickCamp'
enableGitInfo = true

[build]
  [build.buildStats]
    enable = true

[[cascade]]
  [cascade.sitemap]
    disable = true
  [cascade.target]
    kind = '*'
    path = '{/data,/data/**,/parts,/parts/**}'
[[cascade]]
  [cascade.build]
    render = 'never'
  [cascade.target]
    kind = '{taxonomy,term}'
    path = '{/parts,/size,/size/**,/tags,/tags/**,/uses,/uses/**}'
[[cascade]]
  outputs = ["csv"]
  [cascade.target]
    kind = "{term}"
    path = '/parts/**'

[imaging]
  anchor = 'Center'
  bgColor = '#ffffff'
  hint = 'drawing'
  quality = 95
  resampleFilter = 'Lanczos'

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.145.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[params]
  dateFormat = 'Jan. 2, 2006'

[taxonomies]
  part = 'parts'
  size = 'size'
  uses = 'uses'
  tag  = 'tags'

[uglyURLs]
  _data = true